### PR TITLE
Add library configuration object

### PR DESCRIPTION
**Pull request by ezekg**
Implemented along with this is a configuration option to define a custom parameter parser for the `:jsonapi` mime-type, something which I think is a needed addition.

### CODE REVIEW

**Comment by beauby** [comment]
Thanks for the PR @ezekg! How do you feel about a simple boolean option to prevent registering the params parser? (e.g. `JSONAPI::Rails.configure { |config| config.register_params_parser = false }`)

**Comment by ezekg** [comment]
I actually experimented with that first, along with adding an option for toggling the registration of the jsonapi mime type in case it's being registered another way. But the library depends on both of those being defined a certain way (jsonapi mime type being under `:jsonapi`, instead of say an alias for the `:json` mime type). So in the end, both of those can't really be 'disabled' (instead, they're just defined elsewhere), so I figured exposing the definition itself was the best option.

Would you rather implement toggles instead of exposing the params parser?

**Comment by beauby** [comment]
@ezekg Right, so rails expects a params parser for the `application/vnd.api+json` mime type once it is registered (which jsonapi-rails does). The reason why I favor a boolean config to avoid declaring a params parser is that an existing app with a custom params parser for the jsonapi mime type wouldn't have to move that parser definition. 

Ideally, jsonapi-rails should allow a more fine-grained configuration of what it declares in the initializers (registering params parser, registering renderer), and ensure it does not redefine the `:jsonapi` mime type if already defined.

**Comment by ezekg** [comment]
Okay yeah, that sounds good to me. I'll modify the PR to implement it that way.

**Comment by ezekg** [comment]
First pass on the changes we discussed. Do we want to implement any validation to ensure that the mime-type/parser is never redefined? (Or error handling in the cases where they are not defined?) I'm now able to implement like so, which is great:

```ruby
# config/initializers/jsonapi.rb

# Register JSON API mime-type
Mime::Type.register "application/vnd.api+json", :jsonapi, %W[
  application/vnd.api+json
  application/json
  text/x-json
]

# Register parameter parser for JSON API mime-type to transform param keys from
# camel case to snake case
ActionDispatch::Request.parameter_parsers[:jsonapi] = -> (raw_post) {
  data = ActiveSupport::JSON.decode raw_post
  data = { _json: data } unless data.is_a? Hash
  data.deep_transform_keys! &:underscore
  data.with_indifferent_access
}

# Make sure jsonapi/rails doesn't overwrite our registrations
JSONAPI::Rails.configure do |config|
  config.register_parameter_parser = false
  config.register_mime_type = false
end
```

**Comment by beauby** [comment]
Safeguards for not overriding already registered mime type/params parser seems like a good idea (we just have to make sure that jsonapi-rb's code is ran *after* the user-supplied rails initializer) . 
Regarding warnings for when they're not, I think it is not necessary as long as the default behavior is to register them.

**Comment by ezekg** [comment]
Yeah, so right now it looks like we're hooking into [the controller setup](https://github.com/ezekg/jsonapi-rails/blob/d9ef54a998ac391b3ef3989637c64a0785e69ed3/lib/jsonapi/rails/railtie.rb?ts=2#L20), which I believe is after user-supplied initializers are run. Is that correct? If so, we should be safe to do a little bit of validation.

**Comment by beauby** [comment]
> hooking into the controller setup, which I believe is after user-supplied initializers are run. Is that correct? 

I don't know, but I'll look into it. Other than that, this PR looks really good, apologies for taking literally months to review it 🙄

**Comment by ezekg** [comment]
Haha It's cool. I've been using my fork in prod for a few months and things are good. 👍

**Comment by ezekg** [comment]
Are you still wanting to move forward on this, @beauby?

**Comment by beauby** [comment]
@ezekg Yes, definitely. I just want to take care of `ActiveModel::Errors` serialization first, but this is on my radar!

**Comment by beauby** [comment]
The time has finally come 🙏
Thanks again for this @ezekg!

**Pull request merged**
